require 'landslider/entities/ws_search'
require 'landslider/entities/ws_search_criterion'
require 'landslider/entities/ws_account_note_search'
require 'landslider/entities/ws_contact_note_search'
require 'landslider/entities/ws_lead_note_search'
require 'landslider/entities/ws_opportunity_note_search'